/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

/**
 *
 * @author barat
 */
public class Vendas extends javax.swing.JPanel {

  /**
   * Creates new form Vendas
   */
  public Vendas() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    btn_registar_venda = new javax.swing.JButton();
    btn_historico_vendas = new javax.swing.JButton();
    btn_voltar = new javax.swing.JButton();

    jLabel1.setBackground(new java.awt.Color(0, 255, 255));
    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 255));
    jLabel1.setText("Menu de Vendas");

    btn_registar_venda.setText("Registar uma venda");
    btn_registar_venda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_registar_vendaActionPerformed(evt);
      }
    });

    btn_historico_vendas.setText("Ver histórico de vendas");

    btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-voltar.jpg"))); // NOI18N
    btn_voltar.setText("Voltar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btn_voltar)
        .addGap(57, 57, 57))
      .addGroup(layout.createSequentialGroup()
        .addGap(154, 154, 154)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(btn_historico_vendas)
          .addComponent(btn_registar_venda))
        .addContainerGap(145, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addComponent(jLabel1)
        .addGap(79, 79, 79)
        .addComponent(btn_registar_venda)
        .addGap(40, 40, 40)
        .addComponent(btn_historico_vendas)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        .addComponent(btn_voltar)
        .addGap(31, 31, 31))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btn_registar_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registar_vendaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_registar_vendaActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_historico_vendas;
  private javax.swing.JButton btn_registar_venda;
  private javax.swing.JButton btn_voltar;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
